### ISSUE TITLE
수정요청: IR/IV 테이블이 아닐경우 소스 테이블이 truncate 되지 않도록

### ISSUE THREAD

**Issue by vine-nam** [vine-nam/Java_DBtoDB_Migration#3]
https://github.com/vine-nam/Java_DBtoDB_Migration/blob/dc7f03ba3e8243eb88cb4b844e6563f7655c8d2c/src/main/DBExecute.java#L132

**Comment by YeHunMoon** [comment]
return 값 null 처리로 수정 완료했습니다😀
